[project]
name = "ai-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.123.9",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
